### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2


### dataset
dataset: MATH_training_split_long_cot
template: qwen
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 32
cutoff_len: 8192

### output
output_dir: saves/Qwen2.5-3B-Instruct/MATH_training_split_long_cot

logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
